# Assignment 2: NumPy Part 2

## Learning Objectives
This lesson meets the following learning objectives:

- The ability to use Python data structures provided in NumPy.

## Instructions
Read through all of the text in this page. This assignment provides step-by-step training divided into numbered sections. The sections often contain embeded exectable code for demonstration.  Section headers with icons have special meanings:  

- <i class="fas fa-puzzle-piece"></i> The puzzle icon indicates that the section provides a practice exercise that must be completed.  Follow the instructions for the exercise and do what it asks.  Exercises must be turned in for credit.
- <i class="fa fa-cogs"></i> The cogs icon indicates that the section provides a task to perform.  Follow the instructions to complete the task.  Tasks are not turned in for credit but must be completed to continue progress.

Review the list of items in the **Expected Outcomes** section to check that you feel comfortable with the material you just learned. If you do not, then take some time to re-review that material again. If after re-review you are not comfortable, do not feel confident or do not understand the material, please ask questions on Slack to help.

Follow the instructions in the **What to turn in** section to turn in the exercises of the assginment for course credit.

## <i class="fa fa-cogs"></i> Notebook Setup
First, we must import the NumPy library. 

In [2]:
# Import numpy
import numpy as np

## 1. Basic Indexing: Subsets and Slicing
### 1.1. Learning

We often want to consider a subset of a given array. You will recognize basic subsetting as it is similar to indexing of Python lists.  

The following code examples demonstrate how to subset a NumPy array:

```python
# Get items from "start" to "end" (but the end is not included!)
a[start:end] 

# Get all items from "start" through the rest of the array
a[start:]    

# Get items from the beginning to "end" (but the end is not included!)
a[:end]      
```
Similarly to Python lists, retriving elements from the end of a NumPy array uses negative indexing.  Execute the example code below to see a demonstration:

In [3]:
# Create a 5 x 2 array of random numbers
demo_g = np.random.random((5,2))
print(demo_g)

# Get the last item from the last 'row':
demo_g[-1, -1]

[[0.49530926 0.78024756]
 [0.84589572 0.50829896]
 [0.6772279  0.39074472]
 [0.70679212 0.51968571]
 [0.13876589 0.36911086]]


0.3691108638165469

### 1.2. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [20]:
array1 = np.random.random((3,3,3))

print(array1)

demo1 = array1[1]

print(demo1)

demo2 = array1[-1,-1]

print(demo2)

demo3 = array1[1:3]

print(demo3)

[[[0.93253245 0.3306618  0.26538983]
  [0.52832034 0.5341167  0.48365743]
  [0.8098721  0.69477967 0.49030855]]

 [[0.36346626 0.00792729 0.04758347]
  [0.50995744 0.99540746 0.53691578]
  [0.55070297 0.39402525 0.90055125]]

 [[0.60147371 0.87055957 0.53083063]
  [0.41900315 0.37612304 0.76238928]
  [0.45888067 0.71566477 0.72138126]]]
[[0.36346626 0.00792729 0.04758347]
 [0.50995744 0.99540746 0.53691578]
 [0.55070297 0.39402525 0.90055125]]
[0.45888067 0.71566477 0.72138126]
[[[0.36346626 0.00792729 0.04758347]
  [0.50995744 0.99540746 0.53691578]
  [0.55070297 0.39402525 0.90055125]]

 [[0.60147371 0.87055957 0.53083063]
  [0.41900315 0.37612304 0.76238928]
  [0.45888067 0.71566477 0.72138126]]]


## 2. "Fancy" Indexing

Fancy indexing allows you to provide an array of indicies or an array of boolean values in order to subset an array.


### 2.1 Using a Boolean Array for Indexing
Rather than using an index range, as shown in the previous section, we can provide an array of boolean values where `True` indicates that we want the value in the position where `True` is found, and `False` indicates we do not want it.  Creating these boolean arrays is simple if we use conditional statements. 

For example, review and then execute the following code:

In [ ]:
# Create a 5 x 2 array of random numbers
demo_g = np.random.random((5,2))

# Find all values in the matrix less than 0.5
demo_g < 0.5

Notice the return value is an array of boolean values.  True indicates if the value was less than 0.5. False indicates it is greater or equal. We can use this boolean array as an index for the same array to return only those values satisfy the boolean condition. Try executing the following code:

In [ ]:
demo_g[demo_g < 0.5]

Or alternatively:

In [ ]:
sig_list = demo_g < 0.5
demo_g[sig_list]

### 2.2. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [32]:
demo_boo = np.random.random((5,3))

print(demo_boo)

demo_boo[demo_boo>.5]

less_list = demo_boo < .5
demo_boo[less_list]

demo_boo[demo_boo ==.193]

andor = demo_boo < .5 and >.1
demo_boo[andor]


SyntaxError: invalid syntax (2398015907.py, line 12)

### 2.3 Using exact indicies

Alternatively, if there are specific elements from the array that we want to retrieve we can provide the specific numeric indices.  

For example, review and then execute the following code:

In [ ]:
# Generate a list of 500 random numbers
demo_f = np.random.random((500))

# Retreive 5 random numbers from the list
demo_f[[0,100,200,300,400]]

## 3. Intermission -- Getting Help

Python has a built in function, `help()`, we can call on any object (anything) to find out more about it. As we move deeper into the functions provided by most packages, we often need to know exactly what a given function expects as arguments.

The output of these `help()` calls can be long. Try executing the following help call for the `np.array` attribute:

In [ ]:
# Call help on anything from a package.
help(np.array)

Additionally, we can get help about an object that we created! Execute the following code to try it out:

In [ ]:
# Call help on an object we created.
x = np.array([1, 2, 3, 4])
help(x)

### 3.1 <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [36]:
#sample_array = np.concatenate([1,2,5,6,7])
#help(sample_array)

help(np.concatenate)

help(np.vstack)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

## 4. Manipulating Arrays
Thus far, we have larned to create arrays, perform basic math, aggregate values, and index arrays. Finally, we need to learn to manipulate them by transposing, reshaping, splitting, joining appending, and deleting arrays.

### 4.1 Transposing
Transposing an array is equivalent to flipping it both horizontally and vertically as shown in the following animated image:

<img src="./media/A01-Matrix_transpose.gif">

(image source: https://en.wikipedia.org/wiki/Transpose)

Numpy allows you to tranpose a matrix in one of two ways:

+ Using the `transpose()` function
+ Accessing the `T` attribute.

Execute the following code examples to see an example of an array transpose

In [37]:
# Create a 2 x 3 random matrix
demo_f = np.random.random((2,3))

print("The original matrix")
print(demo_f)

print("\nThe matrix after being tranposed")
print(np.transpose(demo_f))

print("\nThe tranposed matrix from the T attribute")
print(demo_f.T)


The original matrix
[[0.15233921 0.74328323 0.79933708]
 [0.15155957 0.2683199  0.62065316]]

The matrix after being tranposed
[[0.15233921 0.15155957]
 [0.74328323 0.2683199 ]
 [0.79933708 0.62065316]]

The tranposed matrix from the T attribute
[[0.15233921 0.15155957]
 [0.74328323 0.2683199 ]
 [0.79933708 0.62065316]]


### 4.2 <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create a matrix of any size and transpose it.

In [41]:
print("The original matrix")
sample_matrix = np.random.random((5,2))
print(sample_matrix)

print("The transposed matrix")
print(np.transpose(sample_matrix))


The original matrix
[[0.9684856  0.24799024]
 [0.58854918 0.96959138]
 [0.27301647 0.85156405]
 [0.74454971 0.28458573]
 [0.1596036  0.50168791]]
The transposed matrix
[[0.9684856  0.58854918 0.27301647 0.74454971 0.1596036 ]
 [0.24799024 0.96959138 0.85156405 0.28458573 0.50168791]]


### 4.3 Reshaping and Resizing
You can change the dimensions of your array by use of the following two functions:
 + `resize()`
 + `reshape()`
 
The `resize()` function allows you to "stretch" your array to increase its size.  This can be useful if you need to add more data to an existing array or you need to adjust it prior to performing arithmatic and Broadcasting.

The `reshape()` function allows you to change the dimensions of an existing array. For example, if you have a _3 x 2_ array you can change it to a _6 x 1_ array using the `reshape()` function without losing the data values in the array.

Examine and execute the following code adapted from the DataCamp Tutorial:

In [ ]:
# Create an array x of size 4 x 1. Print the shape of `x`
x = np.array([1,1,1,1])
print(x.shape)

# Resize `x` to ((6,4))
np.resize(x, (6,4))

Notice how the array was resized from a _4 x 1_ to a _6 x 4_ array.

In [ ]:
# Reshape `x` to (2,6)
x = np.array([1,2,3,4])
print("\noriginal:")
print(x)
print("\nreshaped:")
print(x.reshape((2,2)))

### 4.4 <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [48]:
new_matrix = np.array([1,2,3,3,4])

resized_matrix = new_matrix.reshape((3,5))






ValueError: cannot reshape array of size 5 into shape (3,5)

### 4.5 Appending Arrays
Sometimes, you may want to want to append one array to another.  You can append one array to another using the `append()` function.  You can append an array to any dimension.  Remember that NumPy arrays have **axes**.  When you append one array to another you must specify the axes (e.g. row or column for 2D array) that you want to append. Axes are identified using a numeric index starting from 0, therefore:

+ `0`: the first dimension (the columns, or x-axis)
+ `1`: the second dimension (the rows, or y-axis)
+ `2`: the third dimension (the z-axis)
+ `3`: the fourth dimension
+ etc...

For example, examine and execute this code borrowed from the DataCamp tutorial:

In [ ]:
# Append a 1D array to your `my_array`
my_array = np.array([1,2,3,4])
new_array = np.append(my_array, [7, 8, 9, 10])

# Print `new_array`
print(new_array)

# Append an extra column to your `my_2d_array`
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
new_2d_array = np.append(my_2d_array, [[7], [8]], axis=1)

# Print `new_2d_array`
print(new_2d_array)

In the code above, for the first example, the array `[7, 8, 9, 10]` is appended or added to the existing 1D `my_array`.  For the second example, the values `7` and `8` are added to the rows (note the `axis=1` parameter.

### 4.6. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [51]:
threedarray= np.random.random([3,3,3])

new_array = np.append(threedarray, [1,3,3])

print(new_array)



TypeError: 'builtin_function_or_method' object is not subscriptable

### 4.7. Inserting and Deleting Elements
You can easily add a new element, or elements to an array using the `insert()` and `delete()` functions.  

### 4.8. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.


In [55]:
help(delete())

NameError: name 'delete' is not defined

### 4.9 Joining Arrays
There are a variety of functions for joining arrays:

 + `concatenate()`
 + `vstack()`
 + `hstack()`
 + `column_stack()`

Each of these functions is used in the following code borrowed from a [DataCamp](https://www.datacamp.com/) tutorial. Examine and execute the following code cell:

In [56]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


### 4.10. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Execute the code (as shown above).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question
  + Can you identify what is happening with each of them?

In [ ]:
Yes, for concatenate, the first and second arrays were combined into one array. Vstack, vertically stacked the two arrays by rows. Hstack, horizontally stacks the two arrays  adn column stack stacks the two arrays by column

### 4.11. Splitting an Array
You may find that you need to split arrays. The following functions allow you to split horizontally or vertically:
 + `vsplit()`
 + `hsplit()`
 
Examine and execute the following code borrowed from the DataCamp Tutorial:

In [57]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


### 4.12. <i class="fas fa-puzzle-piece"></i> Practice

In the cell below notebook, perform the following.

+ Execute the code (as shown above).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question
  + Can you identify what is happening with each of them?

In [ ]:
The hsplit function splits the arrays in half by the columns while the vspllit function splits the array by the row.

## Expected Outcomes
At this point, you should feel comfortable with the following:
- Indexing and subsetting of arrays.
- "Fancy" indexing
- Tranposing arrays
- Reshaping arrays
- Inserting and deleting elements
- Joining arrays
- Splitting an array

## What to Turn in?
Be sure to **commit** and **push** your changes to this notebook.  All practice exercises should be completed.  Once completed, send a **Slack message** to the instructor indicating you have completed this assignment. The instructor will verify all work is completed. 